CHANGELOG.md
README.md
src/main/java/eu/xenit/gradle/docker/DockerBuildExtension.java
src/main/java/eu/xenit/gradle/docker/tasks/internal/DeprecatedTask.java
src/main/java/eu/xenit/gradle/tasks/ResolveWarTask.java

Update deprecation messages for behavior that will be removed or changed in 5.0.0

Update readme and changelog for release of version 4.0.0.

---

src/main/java/eu/xenit/gradle/alfresco/DockerAlfrescoPlugin.java

Include base war as input for the `mergeXWar` tasks

---

src/main/java/eu/xenit/gradle/docker/DockerConfigPlugin.java

Remove DOCKER_TLS_VERIFY environment variable.

---

CHANGELOG.md
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/git-without-commits/Dockerfile
src/integrationTest/reproductions/git-without-commits/_git/HEAD
src/integrationTest/reproductions/git-without-commits/_git/config
src/integrationTest/reproductions/git-without-commits/build.gradle
src/main/java/eu/xenit/gradle/git/JGitInfoProvider.java

Handle edgecase where a git repo is initialized, but does not have commits

---

.travis.yml

The previous construction to run the publishing only on tags seems not to be working

Use deploy block for the deployment stage

---

CHANGELOG.md
src/main/java/eu/xenit/gradle/docker/DockerConfigPlugin.java

Always configure DOCKER_HOST envvar for docker-compose.

---

src/main/java/eu/xenit/gradle/docker/DockerBuildBehavior.java
src/main/java/eu/xenit/gradle/docker/DockerBuildExtension.java

Prevent illegal characters in docker tags through encoding

Automatic tags strict

---

src/integrationTest/examples/example-docker-plugin/build.gradle
src/integrationTest/examples/example-docker-plugin/docker-compose.yml
src/main/java/eu/xenit/gradle/docker/DockerBuildBehavior.java
src/main/java/eu/xenit/gradle/docker/DockerConfigPlugin.java

Only react to it by configuring environment variables when we detect the plugin to be present.
Fixes #58

5.0: Do not automatically apply docker-compose plugin

---

.travis.yml
README.md
UPGRADING-5.0.md
build.gradle
src/integrationTest/java/eu/xenit/gradle/testrunner/AbstractIntegrationTest.java
src/integrationTest/reproductions/alfresco-amp-dependency-order/build.gradle
src/main/java/eu/xenit/gradle/docker/DockerBuildBehavior.java
src/main/java/eu/xenit/gradle/tasks/DockerfileWithCopyTask.java
src/test/java/eu/xenit/gradle/alfresco/DockerAlfrescoPluginTest.java

Fixes #55 
Fixes #65 (gradle-docker-plugin 6 supports reading credentials store)

Support for gradle 6.0

---

CHANGELOG.md
build.gradle
src/main/java/eu/xenit/gradle/docker/DockerBuildBehavior.java

This fixes https://github.com/bmuschko/gradle-docker-plugin/issues/895

Update bmuschko/gradle-docker-plugin to 6.1.2

---

CHANGELOG.md
build.gradle

* Update gradle plugins
* Remove unused dependencies
* Shadow non-plugin dependencies into the plugin

Cleanup gradle build

---

.travis.yml
src/integrationTest/java/eu/xenit/gradle/testrunner/AbstractIntegrationTest.java
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-98/build.gradle
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/AbstractInjectFilesInWarTask.java

- Add test to check if we actually install AMPs, DEs and SMs
- Run tests on Gradle 6.1
- Fixes #98

Workaround for #98

---

src/integrationTest/java/eu/xenit/gradle/testrunner/AbstractIntegrationTest.java
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-96/build.gradle
src/integrationTest/reproductions/issue-96/docker/Dockerfile
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeConventionImpl.java

#96 Replace DockerBuildImage#doLast lambda actions with inner classes

---

src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-97/build.gradle
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/StripAlfrescoWarTask.java

Label image with installed AMPs, DEs and SMs

---

src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-107/build.gradle
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java

Fix lean image

---

src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/CircularModuleDependencyException.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/MissingModuleDependencyException.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleDependencySorter.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleException.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleInstallationException.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/InstallAmpsInWarTask.java

Improve mmt error message

---

src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java
src/test/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPluginTest.java

GH-128 Move initialize of removeExistingWar out of afterEvaluate

---

src/main/java/eu/xenit/gradle/docker/DockerBuildBehavior.java

Remove docker image label with commit message.

---

CHANGELOG.md
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeExtensionOverride.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeSettingsOverride.java

This PR also contains some required code changes to use new features/bug fixes from the gradle-docker-compose-plugin

Prepare release 5.0.6

---

src/integrationTest/examples/docker-compose-example/docker-compose.nested.yml
src/integrationTest/examples/docker-compose-example/docker-compose.yml
src/main/java/eu/xenit/gradle/docker/compose/DockerComposePlugin.java

Apply the `eu.xenit.docker-config` plugin when `eu.xenit.docker-compose` is applied.

---

CHANGELOG.md
README.md
appveyor.yml

Enable npipe support for Docker on windows

---

CHANGELOG.md
README.md
src/integrationTest/examples/docker-compose-example/build.gradle
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeConvention.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeConventionImpl.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeExtensionOverride.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeSettingsOverride.java
src/main/java/eu/xenit/gradle/docker/compose/ReplayableComposeConventionImpl.java
src/test/java/eu/xenit/gradle/docker/compose/DockerComposeConventionImplTest.java

Add dockerCompose.fromProject() with user-configured environment variable

---

CHANGELOG.md
src/integrationTest/examples/alfresco-war-platform/build.gradle
src/integrationTest/java/eu/xenit/gradle/testrunner/ExampleRunner.java
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/gradle/backports/JvmEcosystemPluginBackport.java
src/main/java/eu/xenit/gradle/docker/internal/GradleVersionRequirement.java

Add support for platform() & enforcedPlatform() with docker-alfresco plugin

---

src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-107/build.gradle

This reverts commit 27179b86c46e298869c7b318b0eefec623721c01.

Revert "Ignore test awaiting bugfix gradle-docker-plugin dependency"

---

build.gradle

Update gradle-docker-plugin to 9.3.2
