xenit-eu/alfresco-docker-gradle-plugin

build.gradle

Plugin portal only accepts empty, sources and javadoc classifiers, and our 'all' classifier got rejected

Give the shadowJar an explicit empty classifier.

---

src/integration-test/examples/dependent-subprojects/dependent/build.gradle

afterEvaluate is no longer needed, as the createDockerFile task is available immediately.
The buildLabels task is also deprecated, so we should no longer point people to it

Update dependent subprojects example to remove afterEvaluate

---

CHANGELOG.md
build.gradle
src/integration-test/examples/example-docker-plugin/docker-compose.yml
src/integration-test/java/eu/xenit/gradle/testrunner/ExampleRunner.java

First commit added a test that fails with:
```
Exit-code 1 when calling docker-compose, stdout: The GITHUB variable is not set. Defaulting to a blank string.
No such service: The GITHUB variable is not set. Defaulting to a blank string.
```
See https://travis-ci.org/xenit-eu/alfresco-docker-gradle-plugin/jobs/458193914#L825
Updating avast dependency fixes it

DEVEM-342 fixes failing composeUp with warnings on stderr

---

.travis.yml
CHANGELOG.md
README.md
build.gradle
src/integrationTest/examples/example-docker-plugin/build.gradle
src/integrationTest/examples/publish-war/build.gradle
src/integrationTest/java/eu/xenit/gradle/testrunner/ExampleRunner.java
src/main/java/eu/xenit/gradle/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/alfresco/tasks/internal/DeprecatedMergeWarTask.java
src/main/java/eu/xenit/gradle/tasks/InjectFilesInWarTask.java
src/main/java/eu/xenit/gradle/tasks/MergeWarsTask.java
src/main/java/eu/xenit/gradle/tasks/ResolveWarTask.java
src/main/java/eu/xenit/gradle/tasks/WarOutputTask.java

Creating a new one for #17 because the source branch is gone
To make it easier to publish alfresco/share war as artifact, I made it extend the `Zip` task.
However, this change makes it difficult to keep supporting the `setOutputWar()` method to choose where you want to place the output war.
It also changes the location in the build directory where the output war is located by default.
Given that the `MergeWarTask` was not part of the documented public API, we should be able to change it in a minor release.
This change will deprecate `mergeAlfrescoWar` and `mergeShareWar`, replacing them with `alfrescoWar` and `shareWar` tasks, to be more consistent with the naming of other Gradle tasks.
This change will also make the `alfrescoWar` and `shareWar` tasks part of the public API, and they are …

Make MergeWarTask extend the Zip task

---

CHANGELOG.md
src/main/java/eu/xenit/gradle/tasks/StripAlfrescoWarTask.java
src/main/java/eu/xenit/gradle/tasks/Util.java

When we only unmount a particular file that is being worked on, there is no risk of stomping upon other threads working with other `TFile`s in parallel.
Fixes #38

Only unmount the particular truezip file that is being worked on, instead of unmounting all items

---

CHANGELOG.md
src/main/java/eu/xenit/gradle/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/tasks/DockerfileWithWarsTask.java
src/main/java/eu/xenit/gradle/tasks/InjectFilesInWarTask.java
src/main/java/eu/xenit/gradle/tasks/ResolveWarTask.java
src/main/java/eu/xenit/gradle/tasks/Util.java
src/main/java/eu/xenit/gradle/tasks/WarInputTask.java
src/test/java/eu/xenit/gradle/alfresco/DockerAlfrescoPluginTest.java

Dependencies were resolved during the configuration of the project, which resulted in the alfresco and share wars being always being downloaded, even if they are not used in the current run.
This hurts especially when running projects like docker-alfresco or docker-share, because all the wars are downloaded even if you only want to build one specific version.
This pullrequests makes all tasks operating on the wars to be `@SkipWhenEmpty`, so they are skipped with NO-SOURCE if no war is given to them.
Fixes #36

Lazy resolve baseXWar dependencies

---

CHANGELOG.md
src/integrationTest/examples/add-files-dockerfile/build.gradle
src/integrationTest/examples/add-files-dockerfile/test.sh
src/integrationTest/java/eu/xenit/gradle/testrunner/AbstractIntegrationTest.java
src/integrationTest/java/eu/xenit/gradle/testrunner/ExampleRunner.java
src/main/java/eu/xenit/gradle/tasks/DockerfileWithCopyTask.java
src/main/java/eu/xenit/gradle/tasks/DockerfileWithWarsTask.java

Added 2 overloads for `Dockerfile.copyFile`, with `File, String` and `FileCollection, String`.
In the original `Dockerfile` class, there only is a `copyFile` method that takes `String, String`, which directly adds a COPY instruction. In that case, the file(s) must be present in the build context (the directory where the Dockerfile lives)
The overloads that function, so you can pass any `File` or `FileCollection`. The files will automatically be copied to a folder inside the build context, so they can be added to the image.
Fixes #42

Improve DX to add additional files to an alfresco docker image

---

CHANGELOG.md
README.md
src/integrationTest/examples/add-files-dockerfile/build.gradle
src/integrationTest/examples/add-files-dockerfile/test.sh
src/main/java/eu/xenit/gradle/tasks/DockerfileWithCopyTask.java
src/main/java/eu/xenit/gradle/tasks/DockerfileWithWarsTask.java

When using copySpec to copy a file or directory, the behavior is different depending on if a file or directory is being copied.
Patch up this difference, so when a directory is used with smartCopy, its contents are actually copied instead of a file inside the directory with the same name of the directory.
Fixes #66

Patch up smartCopy to work when copying directory trees

---

src/integrationTest/java/eu/xenit/gradle/testrunner/AbstractIntegrationTest.java
src/main/java/eu/xenit/gradle/tasks/InstallAmpsInWarTask.java
src/main/java/eu/xenit/gradle/tasks/Util.java

We think raceconditions in concurrent truezip usage result in hard to diagnose issues like #72.
Maybe fixes #72

Implement global truezip lock around all operations that use truezip.

---

README.md
src/main/java/eu/xenit/gradle/docker/DockerConfigPlugin.java
src/main/java/eu/xenit/gradle/docker/DockerPlugin.java
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeAutoPlugin.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeConvention.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeConventionImpl.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeExtensionOverride.java
src/main/java/eu/xenit/gradle/docker/compose/DockerComposePlugin.java
src/main/java/eu/xenit/gradle/docker/compose/PluginClasspathChecker.java
src/main/java/eu/xenit/gradle/docker/compose/PluginClasspathPollutionException.java
src/test/java/eu/xenit/gradle/docker/compose/PluginClasspathCheckerTest.java

Our docker-compose plugin performs cross-project configuration trickery
to retrieve and configure tasks from other projects.
This does not always work well. When a plugin is applied in a `plugins {}`
block, Gradle uses classpath isolation to isolate plugins within each
subproject. This leads to ClassCastExceptions when tasks are passed
around, because the plugin classes do not have the same identity
(classes loaded by different classloaders have a different identity).
However, it is possible to work around this issue: child projects
inherit the classloader from their parent project. By adding the plugin
to a common parent project (for example, the root project), the same
plugin classes are shared in all subprojects. It is possible to specify
`apply false` to only load the plugin in that …

Add plugin classpath checks

---

src/main/java/eu/xenit/gradle/docker/DockerConfigPlugin.java

The avast docker-compose plugin tries to determine the IP address to use for TCP checks based on `DOCKER_HOST`. If it can't parse `DOCKER_HOST` as URL, it will set it to 'localhost' for checks.
This does not work when `DOCKER_IP` is set to something else (for example, if you want to bind to a private subnet and set the `eu.xenit.docker.expose.ip` property to that value)
Setting `SERVICES_HOST` will override all guessing and will force the IP to be checked to be the ip that is configured in `eu.xenit.docker.expose.ip`.

Configure docker-compose SERVICES_HOST envvar

---

build.gradle
src/main/java/eu/xenit/gradle/docker/compose/PluginClasspathChecker.java
src/test/java/eu/xenit/gradle/docker/compose/PluginClasspathCheckerTest.java

There was a bug in parsing the disabled flag, and a bug in `withPlugin` in the disabled case where an early return was missing.

Add tests for plugin classpath checker disabled codepaths

---

CHANGELOG.md
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/Util.java

Fixes #72 (maybe)
TrueZip keeps some caches around after it has opened files (and they were not unmounted)
Alfresco MMT code does not unmount the virtual filesystem after it has used them, because they expect it to be thrown away anyways once the process finishes.
However, when build operations are running in a gradle daemon, the same truezip caches are reused across multiple builds. Other tasks that run before the applyAlfrescoAmp task can change AMP files without coordinating with Truezip, leading to the cache being invalid and Truezip searching for archive entries in the wrong place, which hopefully does not contain a valid zip entry header.
Now we make sure to always unmount all files after a Truezip operation, and still keep the global lock while doing so. The lock is also shared …

Always unmount truezip virtual fs after usage

---

src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-50/build.gradle
src/integrationTest/reproductions/issue-50/prepare-alfresco-war/build.gradle
src/integrationTest/reproductions/issue-50/settings.gradle
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/DuplicateModuleException.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleAlreadyInstalledException.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleDependencyResolver.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleDependencySorter.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleInformation.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleInformationFromModuleDetails.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/MergeWarsTask.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/StripAlfrescoWarTask.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/WarInputTask.java
src/test/java/eu/xenit/gradle/docker/alfresco/internal/amp/DummyModuleInformation.java
src/test/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleDependencyResolverTest.java
src/test/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleDependencySorterTest.java

To get this working, I needed to:
1. Fix the dependencies of `stripAlfrescoWar` task: The configuration that is passed to the task should be resolved. Needs a `dependsOn` in case it is a `project()` type dependency.
2. Fix dependencies of `alfrescoWar`/`shareWar`: `applyAlfrescoAmp`, `applyAlfrescoDE` & `applyAlfrescoSM` tasks should be depended on when they are an input to the `alfrescoWar` task, or these tasks would not run.
3. We need ant-style patterns for `StripAlfrescoWarTask`, so we can include all the `module.properties` files that are in the correct location
4. Add checks that you don't reinstall a module that is already installed: The MMT itself just prints a message to stdout and does not fail the build. We want the build to fail when multiple versions of a module are being …

Allow to install AMPs inside a WAR that already has AMPs installed.

---

src/main/java/eu/xenit/gradle/docker/DockerConfigPlugin.java

It is very annoying that DockerBuildImage tries to pull an image when you have no internet access and are running Gradle with the `--offline` flag to avoid network calls (that will fail).
This always disables automatically updating images when running with the `--offline` flag.

Disable automatic pulling in DockerBuildImage when Gradle is running in --offline mode

---

build.gradle

slf4j is already present and used by Gradle itself.
Shadowing it results in a "Failed to load class" message being printed when a shadowed logger is first initialized. This is an annoying message, and a misconfiguration of slf4j.

Do not include log4j in classes to be shadowed

---

CHANGELOG.md
build.gradle

Updating `com.bmushko:gradle-docker-plugin` dependency now that https://github.com/bmuschko/gradle-docker-plugin/pull/913 is merged - thanks @vierbergenlars :medal_sports: 
I can confirm that with this dependency bump, the docker-repo credentials from my `~/.docker/config.json` are now effectively used :+1:

Update dependency com.bmushko:gradle-docker-plugin to 6.4.0

---

src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-114/build.gradle
src/main/java/eu/xenit/gradle/docker/DockerBuildBehavior.java
src/main/java/eu/xenit/gradle/docker/tasks/internal/DockerPushImage.java
src/main/java/eu/xenit/gradle/docker/tasks/internal/NoImagesConfiguredException.java
src/test/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPluginTest.java

It is possible to invoke the pushDockerImage task, even when you have no
tags configured at all. This will result in pushDockerImage completing
succesfully by doing nothing.
This may lead to the user thinking that images were pushed succesfully
when in fact nothing has been pushed.
Since this task is only used for pushing to a docker registry, it is
okay to throw an error when no images are given to it.
The buildDockerImage task can still be used to build images that are
used only for testing locally and do not have to be pushed.

Throw when using pushDockerImage without tags

---

appveyor.yml
src/integrationTest/examples/example-buildargs/.dockerignore
src/integrationTest/examples/example-docker-plugin/.dockerignore
src/integrationTest/reproductions/configure-registry-credentials/.dockerignore
src/integrationTest/reproductions/docker-plugin-without-config/.dockerignore
src/integrationTest/reproductions/git-without-commits/.dockerignore
src/integrationTest/reproductions/gitCommitWithQuoteTag/.dockerignore
src/integrationTest/reproductions/tagfailing/.dockerignore

This project can also be tested on Windows now with appveyor CI.
It needed some hacky edits to docker configuration files to get port 2375 exposed programmatically.
We only run tests for one Gradle version on Windows, as this is primarily used to test platform-dependent configurations. So there is no need to test all Gradle versions.
A succeeding build can be seen here: https://ci.appveyor.com/project/vierbergenlars/alfresco-docker-gradle-plugin
If this is good, we can configure appveyor properly under a xenit user.

Run tests on Windows

---

.travis.yml
build.gradle
src/main/java/eu/xenit/gradle/docker/DockerBuildBehavior.java
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/version/AlfrescoVersion.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/DockerfileWithWarsTask.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/PrefixLog4JWarTask.java
src/main/java/eu/xenit/gradle/docker/tasks/DockerfileWithCopyTask.java
src/main/java/eu/xenit/gradle/docker/tasks/internal/ConsolidateFileCopyInstructionsAction.java
src/test/java/eu/xenit/gradle/docker/alfresco/tasks/DockerfileWithWarsTaskTest.java
src/test/java/eu/xenit/gradle/docker/tasks/internal/ConsolidateFileCopyInstructionsActionTest.java

Make `DockerfileWithWarsTask` a thinner wrapper around `DockerfileWithCopyTask`.
Previously, because files added with `addWar()` were only added during the main task action, all adding happened at the end of the Dockerfile.
This PR re-imagines the `addWar()` command as a special case of `smartCopy()`.
Like the other `Dockerfile` commands, the order in which `addWar()` and other instructions are called determines the order in the resulting Dockerfile.
This allows users to add custom instructions before, after and inbetween `addWar()` commands, allowing for more flexibility.
When using the configuration options exposed by `eu.xenit.docker-alfresco`, this change remains fully backwards compatible. For direct usage of `DockerfileWithWarsTask`, it remains mostly compatible.
The only …

Convert addWar commands to smartCopy

---

src/main/java/eu/xenit/gradle/docker/tasks/DockerfileWithCopyTask.java

When the whole copyFile copySpec is empty, on older Gradle versions (<=5.5), the docker/copyFile directory is not created either, leading to the mkdir() call
failing because the parent directories do not exist.

Fix smartCopy when nothing has been copied at all.

---

.travis.yml
CHANGELOG.md
src/integrationTest/java/eu/xenit/gradle/testrunner/AbstractIntegrationTest.java
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-173-array/build.gradle
src/integrationTest/reproductions/issue-173-empty/build.gradle
src/main/java/eu/xenit/gradle/docker/autotag/DockerAutotagExtension.java

The `autotag.legacyTags` function only accepted a `Set<String>` as argument.
`Set<String>` is a bit annoying to construct in Gradle, so accept `List<String>` as well so array-notation in Groovy works as well.
We can also offer a no-arguments function as a shortcut, so `autotag.legacyTags()` can be used directly instead of `autotag.legacyTags([])`.
Fixes #173

Add overload methods for `DockerAutotagExtension#legacyTags`

---

CHANGELOG.md
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/remove-empty-commands/build.gradle
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/extension/internal/DockerfileWithWarsExtensionImpl.java
src/main/java/eu/xenit/gradle/docker/tasks/internal/ConsolidateFileCopyInstructionsAction.java
src/test/java/eu/xenit/gradle/docker/tasks/internal/ConsolidateFileCopyInstructionsActionTest.java

In some cases, commands with `null` text may be inserted into the instructions stream.
These are removed during the creation of the Dockerfile itself, but are still present when doing COPY consolidation, resulting in a suboptimal consolidation.
Additionally, when 2 series of COPY commands with different targets follow each other, the first entry of the second series was not consolidated properly.

Remove empty commands before doing COPY consolidation

---

CHANGELOG.md
src/main/java/eu/xenit/gradle/docker/DockerBuildExtension.java
src/main/java/eu/xenit/gradle/docker/DockerFileExtension.java
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoExtension.java
src/main/java/eu/xenit/gradle/docker/core/DockerPlugin.java
src/main/java/eu/xenit/gradle/docker/internal/Deprecation.java

When upgrading an other project, I noticed that deprecation warnings were logged even when no user code was touching the deprecated parts anymore.
It turns out that some internal code in the same class was using the deprecated functions, which triggered the warnings.
These warnings are not useful and might send the developer chasing after problems that aren't there.
Replacing the method calls with the properties directly fixes this issue.

Fix deprecation warnings shown incorrectly

---

.github/workflows/ci.yml
src/integrationTest/examples/lean-example/build.gradle
src/integrationTest/examples/publish-war/build.gradle
src/integrationTest/reproductions/alfrescoDE-double-task/build.gradle
src/integrationTest/reproductions/applyamps-subproject/build.gradle
src/integrationTest/reproductions/applyamps-subproject/subproject/build.gradle
src/integrationTest/reproductions/different-version-properties-between-war-and-image-should-fail/build.gradle
src/integrationTest/reproductions/docker-plugin-without-config/build.gradle
src/integrationTest/reproductions/git-without-commits/build.gradle
src/integrationTest/reproductions/gitCommitWithQuoteTag/build.gradle
src/integrationTest/reproductions/issue-107/build.gradle
src/integrationTest/reproductions/issue-114/build.gradle
src/integrationTest/reproductions/issue-133-extension/build.gradle
src/integrationTest/reproductions/issue-133-label/build.gradle
src/integrationTest/reproductions/issue-97/build.gradle
src/integrationTest/reproductions/issue-98/build.gradle
src/integrationTest/reproductions/modifyDockerfile/build.gradle
src/integrationTest/reproductions/same-version-properties-between-war-and-image-should-succeed/build.gradle
src/integrationTest/reproductions/tagfailing/build.gradle

Jcenter is going away, and we don't need the dependency as all required artifacts are in maven central or alfresco public.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Remove all dependencies to the jcenter repository from integration tests

---

CHANGELOG.md
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-191/build.gradle
src/integrationTest/reproductions/issue-191/docker-compose.yml
src/main/java/eu/xenit/gradle/docker/compose/DockerComposeExtensionOverride.java

By default, the methodMissing() implementation of ComposeExtension just creates a new nested ComposeSettings object.
This is not desired for the fromProject() and fromBuildImage() methods, as these are supposed to do some actual work.
If these methods get called with invalid parameters, they should throw an exception instead of falling back to creating a new ComposeSettings object which the user will never expect.
Fixes #191

Throw a MissingMethodException when nonexisting variants of DockerComposeConvention get called

---

CHANGELOG.md
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/PrefixLog4JWarTask.java

Non-annotated properties are deprecated starting from Gradle 7, which will be released soon.
Also include a non-required check that fails when using deprecated functionality, so we can catch cases like this earlier.

Annotate input properties on PrefixLog4JWarTask

---

.github/workflows/ci.yml

Without a SONAR_TOKEN present, it is not possible to execute the sonarqube task to submit to sonarcloud. The task will fail, failing the build.

Disable sonarqube without SONAR_TOKEN

---

build.gradle

shadow 7.0.0 requires Gradle 7.0 to run builds.
We are currently still on Gradle 6.7 for the plugin build.
This reverts commit 98e097364177282c5e396435d8aaf28de598ad39, reversing
changes made to a69db09611d60a7010a60ff85472404d3d2ca787.
Reverts PR #208

Revert "Merge pull request #208"

---

CHANGELOG.md
docs/02-plugin-docker-alfresco.md
src/integrationTest/examples/log4j-prefix-disable/build.gradle
src/integrationTest/examples/log4j-prefix/build.gradle
src/integrationTest/java/eu/xenit/gradle/testrunner/ExampleRunner.java
src/main/java/eu/xenit/gradle/docker/alfresco/DockerAlfrescoPlugin.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/AbstractWarEnrichmentTask.java
src/main/java/eu/xenit/gradle/docker/alfresco/tasks/MergeWarsTask.java
src/main/java/eu/xenit/gradle/docker/config/DockerConfigPlugin.java
src/main/java/eu/xenit/gradle/docker/internal/GradleVersionRequirement.java

Make it possible to disable rewriting log4j.properties

---

src/main/java/eu/xenit/gradle/docker/alfresco/tasks/MergeWarsTask.java

When using the War task type, additional functionality only for Jars/Wars is available:
* modifying manifests
* shortcuts for modifying META-INF, WEB-INF, web.xml

Change MergeWarsTask task type to War

---

CHANGELOG.md
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-229/build.gradle

Overwriting files in an alfresco WAR with an AMP should work, also when using the `alfrescoWar` task.
It appears that this issue was already fixed as a side-effect of #220, where duplicates strategy was
changed from EXCLUDE to INCLUDE.
Fixes #229

Add reproduction for overwriting files in a war with an AMP

---

.github/workflows/ci.yml
src/integrationTest/java/eu/xenit/gradle/testrunner/Reproductions.java
src/integrationTest/reproductions/issue-230/build.gradle

leanImage=true disables injecting a full WAR into a docker image.
However, a skeleton image is an image without an Alfresco WAR inside, so
injecting only the contents of applied amps, DEs and SMs will not work.
Although this is completely user error, we try to save them some
debugging time by failing the image build when we detect that no war is
present (indicated by no version.properties file being present)
Fixes #230

Add test for leanImage on a skeleton image

---

CHANGELOG.md
build.gradle
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/InvalidModuleException.java
src/main/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleInformationAmp.java
src/test/java/eu/xenit/gradle/docker/alfresco/internal/amp/ModuleInformationAmpTest.java

Trying to install a JAR file as an AMP is not the only error that can
occur, people sometimes also try to install the AMP that they just
created, which may not be valid.
In that case, the real cause of the invalid AMP is hidden in the cause
chain, which is not shown by Gradle by default and is hidden behind
`--stacktrace`.
Fixes #227

Add exception message showing cause of invalid AMP

---

CHANGELOG.md
src/integrationTest/reproductions/issue-176-mitigation/gradle.properties
src/integrationTest/reproductions/remove-empty-commands/build.gradle
src/main/java/eu/xenit/gradle/docker/core/DockerPlugin.java
src/main/java/eu/xenit/gradle/docker/tasks/internal/WorkaroundDockerdConsecutiveCopyBugAction.java

We have now hit this issue a couple of times, because the workaround is not enabled by default.
Every time we hit the bug, enabling the feature flag was enough to solve it, without it making things worse.
We keep the feature flag just in case we bump into a case where it breaks.

Activate workaround for docker consecutive copy bug by default

---

build.gradle
settings.gradle

There is something that consumes the version before reckon gets a chance to set it when using reckon in build.gradle
To fix that; move to the reckon settings plugin

Move reckon to settings plugin
